name: 'Simple Echo Test'
description: 'A minimal action that echoes a message'
branding:
  icon: 'code'
  color: 'orange'
inputs:
  message:
    description: 'Message to echo'
    required: false
    default: 'Hello from GitHub Action!'
runs:
  using: 'composite'
  steps:
    - run: echo "${{ inputs.message }}"
      shell: bash
