name: 'File Processor'
description: 'A simple action that processes files'
branding:
  icon: 'file-text'
  color: 'green'
inputs:
  file_path:
    description: 'Path to file to process'
    required: false
    default: 'README.md'
  operation:
    description: 'Operation to perform (count, print)'
    required: false
    default: 'count'
runs:
  using: 'composite'
  steps:
    - name: Process file
      run: |
        if [ "${{ inputs.operation }}" = "count" ]; then
          wc -l "${{ inputs.file_path }}"
        elif [ "${{ inputs.operation }}" = "print" ]; then
          cat "${{ inputs.file_path }}"
        else
          echo "Unknown operation: ${{ inputs.operation }}"
          exit 1
        fi
      shell: bash